### ISSUE TITLE
User Feedback: Zugversuch

### ISSUE THREAD

**Issue by BenjaminRueth** [ChairOfStructuralMechanicsTUM/Mechanics_Apps#2] opened 2017-04-20 11:26 UTC
Actually the Force between 45 and 50 is the most interesting region, but the spacing of the slider is to coarse in order to be able to inspect it. **Why not do a finer spacing?**

**Comment by EmilyBourne** [comment] 2017-04-23 15:01
This should be fixed now, although it requires adding the plastic behaviour in order to place the black dot correctly when the material slips. Do you think this is clearer? Can we close the issue?

**Comment by BenjaminRueth** [comment] 2017-04-23 15:18
I think the higher resolution is it much better now. But I think it also depends on, WHAT exactly you want to explain with this animation. I guess the sudden jump in the graph from 49N to 50N  is intentional due to breaking behaviour? @FrancescaTaddei

**Comment by BenjaminRueth** [comment] 2017-04-23 15:22
By the way: I'm not the expert on the topic and I do not really know what is going to be explained in the lecture using this animation.

I personally think that

* if you just want to show linear elasticity, it's perfectly fine
* if you want to show hysteresis and the fact that by crossing 50N you irreversibly break the material it's also fine

The different sigmas are not really clear to me, but if this is explained by the lecturer I think this is sufficient; but without any further explanation its hard to understand.

**Comment by EmilyBourne** [comment] 2017-04-23 15:43
Francesca's on holiday so I'm not sure we'll get a response from her soon.

I'm not clear on what all the sigmas are either. Sigma_P is the limit of proportionality, Sigma_S seems to be the breaking point, and Sigma_B my be peak strength. Given that no more information was given on the original app, I assume that it must be explained in the lectures.

The sudden break is also present in the original and I think must be the breaking behaviour as it is "the range where strain increases without load" (http://profkodali.blogspot.de/2013/07/plastic-behaviour-of-structures.html).

Francesca had also previously suggested that it could be possible to include the plastic behaviour so I assume that whatever it was designed to show is explained better with the additional behaviour, or at least not explained less well. Although I wonder if it could be helpful to include a reset button to "unstretch" the material

**Closed** 2020-04-01 11:46 UTC
